/**
 * Apex Coder — Agent 2: HTML Agent
 *
 * Consumes the SystemSpec JSON and generates clean, semantic HTML5.
 * Enforces: ARIA attributes, descriptive IDs, no inline CSS/JS.
 *
 * Output: Raw HTML string (body content + full document structure)
 */

import OpenAI from "openai";
import type { SystemSpec } from "./architect-agent.js";
import { getDeepSeekRequestParams, executeCompletionWithContinuation } from "../deepseek-model-router.js";

export async function runHtmlAgent(
  client: OpenAI,
  model: string,
  userMessage: string,
  spec: SystemSpec,
  onStatus?: (msg: string) => void
): Promise<string> {
  onStatus?.("[HTML Agent] Generating semantic DOM structure...");

  // Build a flattened element reference from the spec
  const elementList = spec.components
    .flatMap((c) => c.elements)
    .join(", ");
  const pageList = (spec.pages || [])
    .map((page) => `#view-${page.id} (${page.title}) with route link [data-route="${page.id}"]`)
    .join(", ");

  const systemPrompt = `You are the Apex Coder HTML Specialist Agent. Your role is to generate flawless, semantic HTML5 markup based on a system specification.

CRITICAL RULES:
1. Output ONLY the raw HTML — no markdown, no backticks, no explanation text.
2. Generate a COMPLETE HTML5 document (DOCTYPE → html → head → body).
3. Every interactive element MUST have a descriptive id attribute exactly matching the spec.
4. Use semantic HTML5 elements: <header>, <main>, <section>, <article>, <nav>, <footer>, <aside>.
5. Add ARIA attributes: aria-label, role, aria-describedby where appropriate.
6. NO inline CSS — use class and id attributes only. You MUST NOT include any <style> tags, CSS rules, or stylesheets in this HTML document. Styling is generated by a separate CSS agent. Only output the HTML structure, classes, and IDs.
7. NO inline JavaScript — event handlers go in separate JS. You MUST NOT include any <script> tags or JavaScript code in this HTML document. Interactive logic is generated by a separate JS agent.
8. Include <meta charset>, <meta viewport>, <title>, and a <link> placeholder for fonts. Do NOT include <link> tags to external stylesheets.
9. For Arabic/RTL: add dir="rtl" to <html> and lang="ar".
10. Every section must have an id matching the component spec.
11. Use descriptive, immutable class names (BEM-style or semantic).
12. Buttons must have type="button" (except form submits).
13. Images must have alt attributes.
14. Inputs must have labels and aria-label.
15. UI Structure for Premium Glassmorphism Look: You must use modern, multi-layered nested layouts. Include wrapping containers and semantic classes (e.g. .glass-card, .glass-nav, .glass-panel, .glass-modal, .glass-footer) for all components to support the mandatory Glassmorphism system. All feature lists, service highlights, pricing cards, and testimonials MUST be structured inside CSS Grid/Flexbox wrapper layouts (e.g., .features-grid, .pricing-grid, .testimonials-carousel) and each item must be encapsulated in its own .glass-card. Never output simple, flat vertical text lists directly on the background; encapsulate everything in modern glass cards with borders, shadows, and inline SVGs.
16. Absolute Decorative Elements: Include absolute-positioned decorative elements like grid overlays and background blur blobs (<div class="blur-blob"></div>) inside major sections (especially Hero, Feature, and Testimonial areas) so that accent colors show through the frosted glass elements.
17. Real, engaging Copywriting & Explicit Interaction Targets: Do not use generic placeholders or "lorem ipsum". Write extremely rich, engaging, professional, marketing-ready content. Every button, link, or toggle MUST have a unique, descriptive ID attribute (e.g., #contact-submit-btn, #booking-close-btn, #search-filter-input, #category-tab-1) to allow the JS agent to bind them to real event handlers.
18. Dedicated SVG Icon/Graphics Design: Whenever an icon, logo, badge, avatar, banner background graphic, or vector illustration is needed, you MUST generate a clean, modern, inline <svg> structure. Do NOT use external icon fonts, external libraries, or raster placeholder images for icons or custom graphics. Write detailed, fully scalable, responsive <svg> code with precise viewBox (e.g. 0 0 24 24), path, circle, rect, linearGradient, fill, stroke, and stroke-width parameters. For large illustrations (like the Hero right column), design a complex vector composition (e.g. mock dashboard panels, server nodes, floating abstract geometries with multiple nested path/shape nodes). All SVGs should support currentColor to allow dynamic CSS hover styling.
19. Professionally Matched Real Images: If the user prompt contains an "APEX CURATED IMAGE ASSETS" section, you MUST use those exact "Optimized URL" values in <img src="..."> elements and match each image role to the correct section:
   - hero → first viewport media, full-width image panel, or main visual.
   - product/showcase/gallery → product cards, featured collections, case studies, menu items, or service previews.
   - venue/background → restaurant, hotel, real estate, clinic, or place-focused sections.
   - team → team/profile cards only.
   Use the provided Alt text, width, height, loading="lazy" for secondary images, and fetchpriority="high" for the hero image. Do NOT use random Unsplash URLs when curated assets are available. If no curated image matches a section, use inline SVG/vector UI instead of unrelated placeholders. All icons, logos, badges, and vector shapes must remain inline SVGs.
20. Mock Dashboard / Browser Previews: If the layout has a mock dashboard or browser preview (e.g., in the Hero section), wrap it inside a browser mockup container (.browser-mockup) complete with a top title bar (.mockup-header) containing window control spheres (.mockup-dots containing red, yellow, green circles) and a mock URL bar. This ensures the CSS agent can style it as a realistic 3D floating dashboard panel with zero overflow or clipping.
21. Multi-Page Single-Bundle Router Structure: Generate all planned pages inside one HTML document. Every page must be a direct child or major descendant of <main id="app-router" class="app-router"> and must use:
   - id="view-{page.id}"
   - class="page-view"
   - data-page="{page.id}"
   - aria-labelledby pointing to that page's heading.
   The first page should also include "${spec.uiStateContract?.activeClass || "is-active"}"; inactive pages should include "${spec.uiStateContract?.hiddenClass || "is-hidden"}".
22. Navigation Contract: The navbar must include a route link/button for every planned page using data-route="{page.id}" and href="#{page.id}". Route links must use class "route-link"; the active route must include "${spec.uiStateContract?.activeClass || "is-active"}".
23. Do not split pages into separate files. This must remain one complete HTML bundle with client-side hash routing.

The following element IDs and classes MUST appear in the HTML:
${elementList}

The following page views and route links MUST appear in the HTML:
${pageList || "#view-home (Home) with route link [data-route=\"home\"]"}

Apex Coder UI State & Event Contract:
${JSON.stringify(spec.uiStateContract || {}, null, 2)}

Produce a massive, highly-detailed, and fully-structured HTML document. Write extensive copywriting, add multiple sections, nested layouts, detailed structures, SVG graphics, grids, and components. The HTML code must be extremely detailed and extensive, easily reaching thousands of lines. Do NOT use comments as placeholders (e.g. "<!-- more items here -->"). Never truncate, never write short examples; write out every single element and section completely. Let it exceed thousands of lines to ensure production-grade richness.`;

  const userPrompt = `Generate the complete HTML5 structure for this request:
"${userMessage}"

System Specification:
${JSON.stringify(spec, null, 2)}`;

  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  const completionArgs: any = {
    model,
    messages,
    max_tokens: 16000,
    stream: false,
    ...getDeepSeekRequestParams(model, 0.4),
  };

  const response = await executeCompletionWithContinuation(client, completionArgs);

  let html = response.choices[0]?.message?.content || "";

  // Strip any accidental markdown fencing
  html = html
    .replace(/^```html\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();

  // Basic validation — ensure we got a real HTML document
  if (!html.toLowerCase().includes("<!doctype") && !html.toLowerCase().includes("<html")) {
    html = `<!DOCTYPE html>\n<html lang="${spec.isRTL ? "ar" : "en"}" ${spec.isRTL ? 'dir="rtl"' : ''}>\n<head>\n<meta charset="UTF-8">\n<meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>${spec.projectTitle}</title>\n</head>\n<body>\n${html}\n</body>\n</html>`;
  }

  onStatus?.(
    `[HTML Agent] DOM generated — ${(html.length / 1024).toFixed(1)}KB, ${(html.match(/<[a-z]/gi) || []).length} elements`
  );

  return html;
}
