/**
 * Apex Coder — Phase 4: JS Agent
 *
 * Generates clean, modern JavaScript strictly constrained by the GlobalSelectorMap.
 * Event listeners are bound ONLY to verified IDs.
 * Eliminates all "undefined" target exceptions.
 *
 * Features: ES6+, defensive null-checks, smooth animations, state management.
 */

import OpenAI from "openai";
import type { SystemSpec } from "./architect-agent.js";
import type { GlobalSelectorMap } from "./selector-sync-engine.js";
import { buildSelectorConstraintPrompt, validateAgainstSelectorMap } from "./selector-sync-engine.js";
import { getDeepSeekRequestParams } from "../deepseek-model-router.js";

export async function runJsAgent(
  client: OpenAI,
  model: string,
  userMessage: string,
  spec: SystemSpec,
  selectorMap: GlobalSelectorMap,
  htmlCode: string,
  onStatus?: (msg: string) => void
): Promise<string> {
  onStatus?.("[JS Agent] Generating interactive logic (constrained by selector map)...");

  const constraintBlock = buildSelectorConstraintPrompt(selectorMap);

  // Build HTML structure summary for cross-agent context injection
  const sections = (htmlCode.match(/<section[^>]*>/gi) || []).length;
  const interactives = (htmlCode.match(/<(button|a|input|select|textarea)[^>]*>/gi) || []).length;
  const totalSelectors = (selectorMap.ids?.length || 0) + (selectorMap.classes?.length || 0);
  const htmlSummaryBlock = `=== HTML STRUCTURE SUMMARY (Generated by HTML Agent) ===
Total sections: ${sections}
Interactive elements: ${interactives}
Registered selectors: ${totalSelectors}
Key IDs: ${(selectorMap.ids || []).slice(0, 12).map((t: any) => t.cssSelector).join(", ")}
=== END HTML SUMMARY ===`;

  const interactiveList = selectorMap.interactiveElements
    .map((t) => `${t.cssSelector} (${t.elements.join("/")} element)`)
    .join("\n  ");

  const RUNTIME_CONSTRAINTS = `
=== CRITICAL RUNTIME CONSTRAINTS ===
1. WRAP EVERY DOM OPERATION: Use try-catch or null-guard before ANY querySelector/getElementById call
2. FALLBACK BEHAVIOR: If an element is not found, gracefully skip rather than throw
3. PERFORMANCE BUDGET: No synchronous operation should block for more than 50ms. Use requestAnimationFrame for animations
4. MEMORY MANAGEMENT: Clear all intervals and event listeners when the router navigates away. Track them in a global cleanup array
5. ERROR BOUNDARY: Wrap each page's initialization in try-catch. Failed pages should show a graceful fallback, not crash the app
6. ACCESSIBILITY: Add aria-labels to interactive elements. Ensure keyboard navigation (Tab, Enter, Escape)
7. NO GLOBAL LEAKS: All variables must be scoped. Do not pollute window namespace
=== END RUNTIME CONSTRAINTS ===`;

  const systemPrompt = `You are the Apex Coder JavaScript Specialist Agent. Your role is to write modern, defensive ES6+ JavaScript that binds to ONLY verified DOM elements.

${htmlSummaryBlock}

${constraintBlock}

${RUNTIME_CONSTRAINTS}

INTERACTIVE ELEMENTS (bind event listeners ONLY to these):
  ${interactiveList || "(none identified — use data-* attributes for delegation)"}

JAVASCRIPT QUALITY RULES:
1. Always use const/let — never var.
2. ALL DOM queries MUST use null-checks: const el = document.getElementById('id'); if (!el) return;
3. Use addEventListener — never inline onclick.
4. Use DOMContentLoaded wrapper for all initialization code.
5. Use modern APIs: IntersectionObserver for scroll-reveal animations (automatically adding the ".active" or ".show-animation" class when cards enter the viewport), CSS custom properties via style.setProperty(), and smooth scrollTo.
6. Central State Management: Use a single structured plain JS object (e.g., const state = { currentSlide: 0, activeTab: 'all', searchQuery: '', isModalOpen: false }) to coordinate clicks, scroll positions, active tabs, and modal overlays.
7. Smooth animations: Prefer CSS class toggling over direct style manipulation to ensure hardware-accelerated transitions. Add dynamic micro-interactions (e.g., header shadow and background glass-blur change on scroll, dynamic card transforms). Implement advanced Vanilla JS 3D Tilt effects on premium cards (track mousemove, calculate bounding rect, apply transform: perspective(1000px) rotateX(...) rotateY(...) scale3d(1.02, 1.02, 1.02)) to emulate Stripe/Apple quality interactivity. Use requestAnimationFrame for scroll/mouse event handlers to guarantee 60fps performance.
8. Form handlers & Modals: Implement robust, beautiful client-side validation (e.g., validating email formats, non-empty textareas) with clear visual error feedback (e.g., toggling ".is-invalid" class). On successful submit, show a loading spinner on the submit button, wait 1.5 seconds, then open a custom success modal dialog.
9. Fully-Featured Interactivity & Mandatory Click/Event Actions: You MUST write complete, production-grade, functional implementations for all planned interactive UI elements and EVERY SINGLE button in the HTML document. There must be 0 mock buttons or placeholders, and NO "// TODO" lines. If a button exists, it MUST have a registered click or submit handler that performs a visible, real action:
   - Navigation & Scroll buttons: Must perform smooth scrolling to their targeted sections (e.g., using element.scrollIntoView({ behavior: 'smooth' })).
   - Toggles & Status buttons: Must toggle active states visually (e.g. adding active classes, changing styles, updating text descriptions).
   - Carousel & slider controls: Implement automatic slide transitions using setInterval. Pause autoplay when the user hovers (mouseenter) and resume on mouseleave. Support dot indicators and next/prev arrow clicks. Detect touch/swipe events (touchstart, touchmove, touchend) to calculate delta X and navigate slides. Implement defensive boundary wrapping. Calculate negative translate values correctly in RTL layouts (check if document.documentElement.dir === 'rtl' or isRTL).
   - Filter tabs & Live search: Create a unified filtering function. When a user changes category tabs or types in the live search input, filter elements dynamically: show an item ONLY if it matches BOTH the active category tab AND the search query (case-insensitive title/content match). Toggle visibility smoothly using opacity/scale transition classes.
   - Modal overlays & trigger buttons: Modal overlays must open with scale/opacity fade-in transitions. Close modals when clicking the close button, clicking anywhere outside the modal content box, or pressing the Escape key. Lock body scroll when a modal is active (document.body.style.overflow = 'hidden') and restore it upon closing.
10. LocalStorage Support: Persist key preferences or choices (e.g., user theme preference or recent search query) using localStorage.getItem/setItem.
11. Performance: Debounce window scroll/resize events.
12. Accessibility: Ensure complete keyboard navigation (e.g., allowing Tab index navigation and Space/Enter trigger activation on elements).
13. Multi-Page Client-Side Router: You MUST implement a hash-based single-bundle router:
   - Use the planned pages: ${(spec.pages || []).map((page) => `#${page.id} -> #view-${page.id}`).join(", ") || "#home -> #view-home"}.
   - Listen to hashchange and click events on [data-route].
   - Update window.location.hash when route links are clicked.
   - Toggle page views using ".page-view", "${spec.uiStateContract?.activeClass || "is-active"}", and "${spec.uiStateContract?.hiddenClass || "is-hidden"}".
   - Toggle route link active state using ".route-link" and "${spec.uiStateContract?.activeClass || "is-active"}".
   - Fall back to the first page when the hash is empty or unknown.
   - Never throw if a page view or route link is missing.
14. UI State & Event Contract: Follow this contract literally:
${JSON.stringify(spec.uiStateContract || {}, null, 2)}
${spec.isRTL ? "15. RTL awareness: handle direction-sensitive transitions, slide offsets, or slide directions (e.g., negative translate values in RTL)." : ""}

FEATURES TO IMPLEMENT (based on spec):
${spec.features.map((f) => `- ${f}`).join("\n")}

REFERENCE HTML STRUCTURE (first 3000 chars):
${htmlCode.slice(0, 3000)}

OUTPUT RULES:
1. Output ONLY raw JavaScript — no markdown, no backticks, no explanation.
2. Wrap ALL code inside a DOMContentLoaded event listener.
3. Add JSDoc comments for each function.
4. Handle all null cases defensively before using any DOM element.
5. Do NOT import any external libraries (use vanilla JS only).
6. Write a complete, highly-detailed vanilla JS application. Support comprehensive state management, event listeners for every single button and interactive element, touch carousel handlers, scroll animations, dynamic 3D tilt effects, local storage settings, form validations, search filter algorithms. The JS code must be fully realized, extensive, and easily exceed thousands of lines without using any shorthand, mock comments, or "// TODO" sections. All buttons in the document must have complete functionality. Let it exceed thousands of lines to ensure maximum feature density.`;

  const userPrompt = `Generate complete JavaScript for: "${userMessage}"
Implement all interactive features from the spec. Strictly follow the Global Selector Map.`;

  const messages: OpenAI.Chat.ChatCompletionMessageParam[] = [
    { role: "system", content: systemPrompt },
    { role: "user", content: userPrompt },
  ];

  const completionArgs: any = {
    model,
    messages,
    max_tokens: 16000,
    stream: false,
    ...getDeepSeekRequestParams(model, 0.5),
  };

  const response = await client.chat.completions.create(completionArgs);

  let js = response.choices[0]?.message?.content || "";

  // Strip markdown fencing
  js = js
    .replace(/^```javascript\s*/i, "")
    .replace(/^```js\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/```\s*$/i, "")
    .trim();

  const hasInit = js.includes("DOMContentLoaded") || 
                 js.includes("window.onload") || 
                 js.includes("type=\"module\"") ||
                 js.includes("(function()");
  if (!hasInit && js.length > 10 && !js.includes("export ")) {
    js = `document.addEventListener('DOMContentLoaded', function() {\n${js}\n});`;
  }

  // Auto-fix selector violations with null-guards instead of just warning
  const validation = validateAgainstSelectorMap(js, selectorMap, "js");
  if (!validation.valid && validation.violations && validation.violations.length > 0) {
    console.warn(`[JS Agent] ${validation.violations.length} selector violations. Auto-fixing with null-guards...`);
    let fixedJs = js;
    for (const violation of (validation.violations || [])) {
      const badSelector = violation.selector;
      if (badSelector.startsWith("#") || badSelector.startsWith(".")) {
        const escaped = badSelector.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const pattern = new RegExp(
          `(querySelector|getElementById)\\s*\\(\\s*['"]${escaped}['"]\\s*\\)\\s*;?(?!\\s*if\\s*\\()`,
          'g'
        );
        fixedJs = fixedJs.replace(pattern, `const _el = $&; if (_el) {`);
        // Add closing brace before next statement
        fixedJs = fixedJs.replace(
          new RegExp(`(const _el = (?:querySelector|getElementById)\\s*\\(\\s*['"]${escaped}['"]\\s*\\)\\s*;?\\s*if\\s*\\(_el\\)\\s*\\{)([\\s\\S]*?)\\n(\\s*)(const|let|var|function|if|for|while|return|document\\.|window\\.)`, 'g'),
          '$1$2\n$3};\n$3$4'
        );
      }
    }
    js = fixedJs;
  } else if (validation.valid) {
    console.log("[JS Agent] Selector validation PASSED — all JS selectors verified against DOM");
  }

  onStatus?.(
    `[JS Agent] Logic complete — ${(js.length / 1024).toFixed(1)}KB${
      validation.violations.length > 0 ? ` (${validation.violations.length} selector warnings)` : " (0 selector violations)"
    }`
  );

  return js;
}
