import type { PDFDocument } from "../../../shared/pdf/types.js";
import { escapeHtml } from "../renderers/base-renderer.js";

export function getHeaderTemplate(doc: PDFDocument): string {
  const isRtl = doc.language === "ar";
  const dir = isRtl ? "rtl" : "ltr";
  const align = isRtl ? "right" : "left";
  return `
    <div dir="${dir}" style="width:100%;font-size:8.5px;padding:6px 24px;color:#94a3b8;font-family:Georgia,Cairo,sans-serif;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e2e8f0;box-sizing:border-box;">
      <span style="font-weight:700;letter-spacing:0.12em;color:#64748b;text-align:${align};">APEX AI</span>
      <span style="font-style:italic;">${escapeHtml(doc.title)}</span>
    </div>`;
}

export function getFooterTemplate(doc: PDFDocument): string {
  const isRtl = doc.language === "ar";
  const dir = isRtl ? "rtl" : "ltr";
  const genText = isRtl 
    ? `تم الإنشاء بواسطة Apex AI — ${escapeHtml(doc.date || new Date().toISOString().slice(0, 10))}`
    : `Generated by Apex AI — ${escapeHtml(doc.date || new Date().toISOString().slice(0, 10))}`;
  const pageText = isRtl
    ? `الصفحة <span class="pageNumber"></span> من <span class="totalPages"></span>`
    : `Page <span class="pageNumber"></span> of <span class="totalPages"></span>`;

  return `
    <div dir="${dir}" style="width:100%;font-size:8.5px;padding:6px 24px;color:#94a3b8;font-family:Georgia,Cairo,sans-serif;display:flex;justify-content:space-between;align-items:center;border-top:1px solid #e2e8f0;box-sizing:border-box;">
      <span>${genText}</span>
      <span>${pageText}</span>
    </div>`;
}
