import type { Express } from "express";
import type { Server } from "http";
import { chatRequestSchema } from "../shared/schema.js";
import { detectPdfIntent, formatPdfAsCodeBlock, parsePdfRequest, tryParseAnyPdfFromText, type PDFDocument } from "../shared/pdf.js";
import { processMessage, validateModelAccess, refinePdfDocumentWithAI, generateStructuredPdfFromText, generateMcqResponse } from "./ai-orchestrator.js";
import { randomUUID } from "crypto";
import { runUnboundPipeline } from "./apex-unbound/pipeline.js";
import OpenAI from "openai";
import DOMPurify from "isomorphic-dompurify";
import { cleanJsonString } from "./apex-unbound/architect-agent.js";
import { runApexSearch } from "./apex-search-engine.js";
import { robustJsonParse } from "./json-repair.js";
// PDF modules are loaded lazily (dynamic import) to avoid Vercel
// bundle-size / initialization crashes from puppeteer + katex + prismjs.
// Each route handler imports what it needs at call time.

const previewStore = new Map<string, { html: string; createdAt: number }>();

interface ActiveGeneration {
  messageId: string;
  conversationId: string;
  content: string;
  reasoningContent: string;
  isComplete: boolean;
  error?: string;
  chunks: Array<{ id: string; content?: string; reasoningContent?: string; model?: string; conversationId?: string; totalDuration?: number }>;
  listeners: Array<(event: { type: "chunk" | "done" | "error"; data?: any }) => void>;
}
const activeGenerations = new Map<string, ActiveGeneration>();

function sanitizeFilename(value: string): string {
  return value
    .trim()
    .replace(/[<>:"/\\|?*\u0000-\u001F]/g, "")
    .replace(/\s+/g, "-")
    .slice(0, 80) || "apex-document";
}

function normalizeStructuredPdfDocument(raw: unknown): PDFDocument {
  if (!raw || typeof raw !== "object") {
    throw new Error("Invalid structured PDF document");
  }

  const doc = raw as PDFDocument;
  if (!doc.title || !Array.isArray(doc.sections) || doc.sections.length === 0) {
    throw new Error("Structured PDF document is missing required fields");
  }

  return {
    ...doc,
    theme: doc.theme || "dark",
    pageSize: doc.pageSize || "a4",
    coverPage: typeof doc.coverPage === "boolean" ? doc.coverPage : true,
    tableOfContents: typeof doc.tableOfContents === "boolean" ? doc.tableOfContents : true,
    language: doc.language || "en",
  };
}

async function normalizeChatPdfResponse(userMessage: string, content: string): Promise<string> {
  const parsed = tryParseAnyPdfFromText(content);
  if (parsed) {
    return formatPdfAsCodeBlock(parsed);
  }

  const request = parsePdfRequest(userMessage);
  const title =
    request.language === "ar"
      ? `مستند ${request.topic}`
      : `${request.topic || "Document"} PDF`;

  const { markdownToPdfDocument } = await import("./markdown-to-pdf.js");
  const fallbackDoc = markdownToPdfDocument(content, {
    title,
    language: request.language,
    theme: "dark",
    pageSize: "a4",
    coverPage: true,
    tableOfContents: true,
    metadata: {
      category: "generated-pdf",
      keywords: ["pdf", "chat", request.topic],
    },
  });

  return formatPdfAsCodeBlock(fallbackDoc);
}

// Clean up previews older than 1 hour to prevent memory leaks
setInterval(() => {
  const now = Date.now();
  previewStore.forEach((data, id) => {
    if (now - data.createdAt > 60 * 60 * 1000) {
      previewStore.delete(id);
    }
  });
}, 15 * 60 * 1000); // Check every 15 mins

export async function registerRoutes(
  httpServer: Server,
  app: Express
): Promise<Server> {
  // Chat endpoint — handles conversational exchanges only.
  // PDF and MCQ generation are handled by dedicated endpoints:
  //   POST /api/generate-mcq  — structured quiz generation
  //   POST /api/export/pdf    — PDF document compilation
  app.post("/api/chat", async (req, res) => {
    try {
      const validationResult = chatRequestSchema.safeParse(req.body);

      if (!validationResult.success) {
        return res.status(400).json({
          error: "Invalid request",
          details: validationResult.error.errors,
        });
      }

      const {
        message,
        model,
        mode,
        reasoningLevel,
        subscriptionTier,
        features,
        conversationId,
        messageId,
        conversationHistory,
        userMemoryContext,
        clientLocalTime,
        stream
      } = validationResult.data;

      const isSynthesisPrompt = message.includes("responses generated by the cognitive agents:") || message.includes("responses generated by the 10 cognitive agents:");

      // Standard flow (non-God Mode): Use DeepSeek via orchestrator
      let targetModel = model;

      // Server-side tier validation against the requested model
      if (!validateModelAccess(model, subscriptionTier)) {
        if (stream) {
          res.setHeader("Content-Type", "text/event-stream");
          res.setHeader("Cache-Control", "no-cache");
          res.setHeader("Connection", "keep-alive");
          res.write(`data: ${JSON.stringify({ error: "Access denied", message: `Model ${model} requires a higher subscription tier.` })}\n\n`);
          res.end();
          return;
        }
        return res.status(403).json({
          error: "Access denied",
          message: `Model ${model} requires a higher subscription tier.`,
          requiredAction: "upgrade"
        });
      }

      const activeMsgId = messageId || randomUUID();
      const activeConvId = conversationId || randomUUID();

      let activeGen = activeGenerations.get(activeMsgId);
      if (!activeGen) {
        activeGen = {
          messageId: activeMsgId,
          conversationId: activeConvId,
          content: "",
          reasoningContent: "",
          isComplete: false,
          chunks: [],
          listeners: []
        };
        activeGenerations.set(activeMsgId, activeGen);
      }

      if (stream) {
        res.setHeader("Content-Type", "text/event-stream");
        res.setHeader("Cache-Control", "no-cache, no-transform");
        res.setHeader("Connection", "keep-alive");
        res.setHeader("X-Accel-Buffering", "no");

        // Catch up with accumulated chunks
        activeGen.chunks.forEach(chunk => {
          res.write(`data: ${JSON.stringify(chunk)}\n\n`);
        });

        if (activeGen.isComplete) {
          if (activeGen.error) {
            res.write(`data: ${JSON.stringify({ error: activeGen.error })}\n\n`);
          } else {
            res.write("data: [DONE]\n\n");
          }
          res.end();
          return;
        }

        const listener = (event: any) => {
          if (event.type === "chunk") {
            res.write(`data: ${JSON.stringify(event.data)}\n\n`);
          } else if (event.type === "error") {
            res.write(`data: ${JSON.stringify({ error: event.data })}\n\n`);
            res.end();
          } else if (event.type === "done") {
            res.write("data: [DONE]\n\n");
            res.end();
          }
        };

        activeGen.listeners.push(listener);

        try {
          const processResponse = await processMessage({
            message,
            model: targetModel,
            mode,
            reasoningLevel,
            subscriptionTier,
            features,
            conversationHistory,
            userMemoryContext,
            clientLocalTime,
          }, (chunk) => {
            if (activeGen!.isComplete) return; // ignore chunks if stopped/cancelled
            const chunkData = {
              id: randomUUID(),
              content: chunk.content || "",
              reasoningContent: chunk.reasoningContent || "",
              model,
              conversationId: activeConvId
            };
            activeGen!.content += chunkData.content;
            activeGen!.reasoningContent += chunkData.reasoningContent;
            activeGen!.chunks.push(chunkData);
            activeGen!.listeners.forEach(l => l({ type: "chunk", data: chunkData }));
          });

          if (!activeGen!.isComplete) {
            if (processResponse && processResponse.totalDuration) {
              const durationData = {
                id: randomUUID(),
                totalDuration: processResponse.totalDuration,
                model,
                conversationId: activeConvId
              };
              activeGen!.chunks.push(durationData);
              activeGen!.listeners.forEach(l => l({ type: "chunk", data: durationData }));
            }
            activeGen!.isComplete = true;
            activeGen!.listeners.forEach(l => l({ type: "done" }));
          }
        } catch (err: any) {
          console.error("Message processing failed:", err);
          if (!activeGen!.isComplete) {
            activeGen!.error = err.message || "Failed to process message";
            activeGen!.listeners.forEach(l => l({ type: "error", data: activeGen!.error }));
            activeGen!.isComplete = true;
          }
        } finally {
          const idx = activeGen!.listeners.indexOf(listener);
          if (idx !== -1) {
            activeGen!.listeners.splice(idx, 1);
          }
        }
        return;
      }

      // Non-stream block: await generation directly
      try {
        const processResponse = await processMessage({
          message,
          model: targetModel,
          mode,
          reasoningLevel,
          subscriptionTier,
          features,
          conversationHistory,
          userMemoryContext,
          clientLocalTime,
        }, (chunk) => {
          const chunkData = {
            id: randomUUID(),
            content: chunk.content || "",
            reasoningContent: chunk.reasoningContent || "",
            model,
            conversationId: activeConvId
          };
          activeGen!.content += chunkData.content;
          activeGen!.reasoningContent += chunkData.reasoningContent;
          activeGen!.chunks.push(chunkData);
        });

        activeGen.isComplete = true;

        return res.json({
          id: activeMsgId,
          content: activeGen.content || processResponse.content,
          reasoningContent: activeGen.reasoningContent || processResponse.reasoningContent,
          conversationId: activeConvId,
          model,
        });
      } catch (err: any) {
        activeGen.isComplete = true;
        activeGen.error = err.message;
        return res.status(500).json({ error: "Failed to process message", message: err.message });
      }
    } catch (error) {
      console.error("Chat API error:", error);

      // Handle specific tier validation errors
      if (error instanceof Error && error.message.includes("Access denied")) {
        return res.status(403).json({
          error: "Access denied",
          message: error.message,
        });
      }

      return res.status(500).json({
        error: "Failed to process message",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // GET: Resume live event stream for active generation
  app.get("/api/chat/stream/:messageId", (req, res) => {
    const { messageId } = req.params;
    const activeGen = activeGenerations.get(messageId);

    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");

    if (!activeGen) {
      res.write(`data: ${JSON.stringify({ error: "No active session found for this message" })}\n\n`);
      res.end();
      return;
    }

    // Catch up with accumulated chunks
    activeGen.chunks.forEach(chunk => {
      res.write(`data: ${JSON.stringify(chunk)}\n\n`);
    });

    if (activeGen.isComplete) {
      if (activeGen.error) {
        res.write(`data: ${JSON.stringify({ error: activeGen.error })}\n\n`);
      } else {
        res.write("data: [DONE]\n\n");
      }
      res.end();
      return;
    }

    const listener = (event: any) => {
      if (event.type === "chunk") {
        res.write(`data: ${JSON.stringify(event.data)}\n\n`);
      } else if (event.type === "error") {
        res.write(`data: ${JSON.stringify({ error: event.data })}\n\n`);
        res.end();
      } else if (event.type === "done") {
        res.write("data: [DONE]\n\n");
        res.end();
      }
    };

    activeGen.listeners.push(listener);

    req.on("close", () => {
      const idx = activeGen.listeners.indexOf(listener);
      if (idx !== -1) {
        activeGen.listeners.splice(idx, 1);
      }
    });
  });

  // POST: Stop / cancel active generation on both server and client
  app.post("/api/chat/stop/:messageId", (req, res) => {
    const { messageId } = req.params;
    const activeGen = activeGenerations.get(messageId);
    if (activeGen) {
      activeGen.isComplete = true;
      activeGen.error = "Generation stopped by user";
      activeGen.listeners.forEach(listener => listener({ type: "done" }));
      activeGen.listeners = [];
      activeGenerations.delete(messageId);
    }
    return res.json({ status: "stopped" });
  });

  // GET: Check active generation status
  app.get("/api/chat/status/:messageId", (req, res) => {
    const { messageId } = req.params;
    const activeGen = activeGenerations.get(messageId);
    if (!activeGen) {
      return res.json({ status: "not_found" });
    }
    return res.json({
      status: activeGen.isComplete ? "completed" : "generating",
      content: activeGen.content,
      reasoningContent: activeGen.reasoningContent,
      conversationId: activeGen.conversationId,
    });
  });

  // Subscription validation endpoint
  app.post("/api/subscription/validate", (req, res) => {
    const { model, tier } = req.body;

    if (!model || !tier) {
      return res.status(400).json({ error: "Model and tier are required" });
    }

    const hasAccess = validateModelAccess(model, tier);
    return res.json({ hasAccess });
  });

  // ── DEDICATED MCQ GENERATION ENDPOINT ─────────────────────────────────────
  // This endpoint is the only entry point for structured quiz generation.
  // It uses an isolated system prompt containing only the MCQ protocol —
  // no PDF schema, no multi-agent synthesis instructions.
  // The /api/chat endpoint must never be used for quiz generation to prevent
  // intent overlap and context contamination.
  app.post("/api/generate-mcq", async (req, res) => {
    try {
      const validationResult = chatRequestSchema.safeParse(req.body);

      if (!validationResult.success) {
        return res.status(400).json({
          error: "Invalid request",
          details: validationResult.error.errors,
        });
      }

      const {
        message,
        model,
        mode,
        reasoningLevel,
        subscriptionTier,
        features,
        conversationId,
        conversationHistory,
        userMemoryContext,
        clientLocalTime,
      } = validationResult.data;

      // Tier validation
      if (!validateModelAccess(model, subscriptionTier)) {
        return res.status(403).json({
          error: "Access denied",
          message: `Model ${model} requires a higher subscription tier.`,
          requiredAction: "upgrade",
        });
      }

      // Always stream for quiz generation so the UI can show progress
      res.setHeader("Content-Type", "text/event-stream");
      res.setHeader("Cache-Control", "no-cache");
      res.setHeader("Connection", "keep-alive");

      try {
        await generateMcqResponse(
          {
            message,
            model,
            mode,
            reasoningLevel,
            subscriptionTier,
            features,
            conversationHistory,
            userMemoryContext,
            clientLocalTime,
          },
          (chunk) => {
            res.write(
              `data: ${JSON.stringify({
                id: randomUUID(),
                content: chunk.content || "",
                reasoningContent: chunk.reasoningContent || "",
                model,
                conversationId: conversationId || randomUUID(),
              })}\n\n`
            );
          }
        );
      } catch (err: any) {
        console.error("[/api/generate-mcq] Generation error:", err);
        res.write(`data: ${JSON.stringify({ error: err.message || "Failed to generate quiz" })}\n\n`);
      }

      res.write("data: [DONE]\n\n");
      res.end();
    } catch (error) {
      console.error("[/api/generate-mcq] Route error:", error);
      return res.status(500).json({
        error: "Failed to generate quiz",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  app.post("/api/export/pdf", async (req, res) => {
    try {
      const { document, content, messages, exportType, options } = req.body || {};

      // Dynamic imports — keeps Puppeteer/KaTeX/Prism out of the initial bundle
      const { conversationToPdfDocument, markdownToPdfDocument } = await import("./markdown-to-pdf.js");
      const { buildPdfHtml } = await import("./pdf-engine.js");
      const { optimizePdfDocument } = await import("./pdf-optimizer.js");
      const { pdfJobQueue } = await import("./pdf/index.js");

      let pdfDocument: PDFDocument;

      if (exportType === "structured" && document) {
        pdfDocument = normalizeStructuredPdfDocument(document);
      } else if (exportType === "conversation") {
        pdfDocument = conversationToPdfDocument(Array.isArray(messages) ? messages : content);
      } else if (exportType === "message" && typeof content === "string") {
        pdfDocument = markdownToPdfDocument(content);
      } else {
        return res.status(400).json({ error: "Invalid export request" });
      }

      // Apply smart optimizations
      const optimizedDoc = optimizePdfDocument(pdfDocument, {
        deduplication: true,
        mergeShortParagraphs: true,
        enrichToc: true,
      });

      if (process.env.VERCEL) {
        console.log("ℹ️ Vercel environment detected. Bypassing Puppeteer to return styled HTML print fallback.");
        const html = buildPdfHtml(optimizedDoc);
        return res.status(200).json({
          fallbackHtml: true,
          html,
          title: pdfDocument.title,
        });
      }

      // Queue through the modular priority queue
      const pdfBuffer = await pdfJobQueue.enqueue(optimizedDoc, {
        priority: "high",
        overrides: {
          theme: options?.theme === "light" ? "light" : options?.theme === "dark" ? "dark" : pdfDocument.theme,
          pageSize: options?.pageSize === "letter" ? "letter" : "a4",
        },
      });

      const filename = `${sanitizeFilename(pdfDocument.title)}.pdf`;
      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Disposition", `attachment; filename="${encodeURIComponent(filename)}"; filename*=UTF-8''${encodeURIComponent(filename)}`);
      res.setHeader("Content-Length", pdfBuffer.length);
      res.send(pdfBuffer);
    } catch (error) {
      console.error("PDF generation failed, falling back to styled HTML:", error);

      try {
        const { conversationToPdfDocument, markdownToPdfDocument } = await import("./markdown-to-pdf.js");
        const { buildPdfHtml } = await import("./pdf-engine.js");
        const { optimizePdfDocument } = await import("./pdf-optimizer.js");

        const { document, content, messages, exportType } = req.body || {};
        let pdfDocument: PDFDocument;

        if (exportType === "structured" && document) {
          pdfDocument = normalizeStructuredPdfDocument(document);
        } else if (exportType === "conversation") {
          pdfDocument = conversationToPdfDocument(Array.isArray(messages) ? messages : content);
        } else if (exportType === "message" && typeof content === "string") {
          pdfDocument = markdownToPdfDocument(content);
        } else {
          throw new Error("Invalid export request type for fallback");
        }

        const optimizedDoc = optimizePdfDocument(pdfDocument, {
          deduplication: true,
          mergeShortParagraphs: true,
          enrichToc: true,
        });

        const html = buildPdfHtml(optimizedDoc);
        return res.status(200).json({
          fallbackHtml: true,
          html,
          title: pdfDocument.title,
        });
      } catch (fallbackErr: any) {
        console.error("HTML Fallback generation failed:", fallbackErr.message);
      }

      res.status(500).json({
        error: "Failed to generate PDF",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // Start queuing a PDF job (returns immediately with jobId)
  app.post("/api/pdf/generate", async (req, res) => {
    try {
      const { document, content, messages, exportType, options } = req.body || {};
      const { conversationToPdfDocument, markdownToPdfDocument } = await import("./markdown-to-pdf.js");
      const { optimizePdfDocument } = await import("./pdf-optimizer.js");
      const { pdfJobQueue } = await import("./pdf/index.js");

      let pdfDocument: PDFDocument;

      if (exportType === "structured" && document) {
        pdfDocument = normalizeStructuredPdfDocument(document);
      } else if (exportType === "conversation") {
        pdfDocument = conversationToPdfDocument(Array.isArray(messages) ? messages : content);
      } else if (exportType === "message" && typeof content === "string") {
        pdfDocument = markdownToPdfDocument(content);
      } else {
        return res.status(400).json({ error: "Invalid export request" });
      }

      const optimizedDoc = optimizePdfDocument(pdfDocument, {
        deduplication: true,
        mergeShortParagraphs: true,
        enrichToc: true,
      });

      const { id } = pdfJobQueue.enqueueWithId(optimizedDoc, {
        priority: options?.priority || "normal",
        overrides: {
          theme: options?.theme === "light" ? "light" : options?.theme === "dark" ? "dark" : pdfDocument.theme,
          pageSize: options?.pageSize === "letter" ? "letter" : "a4",
        },
      });

      return res.status(200).json({ jobId: id });
    } catch (error) {
      console.error("PDF queue generation failed:", error);
      res.status(500).json({
        error: "Failed to queue PDF generation",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // SSE progress stream for a running PDF job
  app.get("/api/pdf-progress/:jobId", async (req, res) => {
    try {
      const { jobId } = req.params;
      const { pdfJobQueue } = await import("./pdf/index.js");
      const { initSseResponse, emitPdfProgress, closeSseResponse } = await import("./pdf/streaming/index.js");

      const status = pdfJobQueue.getStatus(jobId);
      if (!status) {
        return res.status(404).json({ error: "Job not found" });
      }

      initSseResponse(res);

      // Initial progress push
      emitPdfProgress(res, {
        jobId,
        stage: status.status,
        progress: status.progress,
        error: status.error,
      });

      if (status.status === "complete" || status.status === "error") {
        closeSseResponse(res);
        return;
      }

      // Listen for progress updates
      const unsubscribe = pdfJobQueue.onProgress(jobId, (event) => {
        emitPdfProgress(res, event);
        if (event.stage === "complete" || event.stage === "error") {
          closeSseResponse(res);
          unsubscribe();
        }
      });

      req.on("close", () => {
        unsubscribe();
      });
    } catch (error) {
      console.error("SSE progress stream error:", error);
      res.status(500).end();
    }
  });

  // Download Route to fetch completed PDF buffer by jobId
  app.get("/api/pdf/download/:jobId", async (req, res) => {
    try {
      const { jobId } = req.params;
      const { pdfJobQueue } = await import("./pdf/index.js");

      const status = pdfJobQueue.getStatus(jobId);
      if (!status) {
        return res.status(404).json({ error: "Job not found" });
      }

      if (status.status !== "complete") {
        return res.status(400).json({ error: "Job is not completed yet" });
      }

      const buffer = pdfJobQueue.getCompletedBuffer(jobId);
      if (!buffer) {
        return res.status(410).json({ error: "Buffer expired or cleared from memory" });
      }

      res.setHeader("Content-Type", "application/pdf");
      res.setHeader("Content-Length", buffer.length);
      res.send(buffer);
    } catch (error) {
      console.error("PDF download failed:", error);
      res.status(500).json({ error: "Failed to download PDF" });
    }
  });

  app.post("/api/pdf/refine", async (req, res) => {
    try {
      const { document, prompt } = req.body;
      if (!document || !prompt) {
        return res.status(400).json({ error: "Document and prompt are required" });
      }
      const refinedDoc = await refinePdfDocumentWithAI(document, prompt);
      return res.json(refinedDoc);
    } catch (error) {
      console.error("PDF refinement endpoint failed:", error);
      return res.status(500).json({
        error: "Failed to refine PDF",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // Quality report for a PDF document
  app.post("/api/pdf/quality-report", async (req, res) => {
    try {
      const { document } = req.body;
      if (!document) {
        return res.status(400).json({ error: "Document is required" });
      }
      const { generateQualityReport } = await import("./pdf-optimizer.js");
      const normalized = normalizeStructuredPdfDocument(document);
      const report = generateQualityReport(normalized);
      return res.json(report);
    } catch (error) {
      console.error("PDF quality report failed:", error);
      return res.status(500).json({
        error: "Failed to generate quality report",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // HTML preview for a PDF document (for in-browser preview)
  app.post("/api/pdf/preview-html", async (req, res) => {
    try {
      const { document } = req.body;
      if (!document) {
        return res.status(400).json({ error: "Document is required" });
      }
      const { buildPdfHtml } = await import("./pdf-engine.js");
      const { optimizePdfDocument } = await import("./pdf-optimizer.js");
      const normalized = normalizeStructuredPdfDocument(document);
      const optimized = optimizePdfDocument(normalized, { deduplication: true, mergeShortParagraphs: true });
      const html = buildPdfHtml(optimized);
      const id = Math.random().toString(36).slice(2, 10);
      previewStore.set(id, { html, createdAt: Date.now() });
      return res.json({ previewId: id, url: `/api/pdf/preview/${id}` });
    } catch (error) {
      console.error("PDF preview-html failed:", error);
      return res.status(500).json({
        error: "Failed to generate preview",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  app.post("/api/pdf/generate-from-text", async (req, res) => {
    try {
      const { text } = req.body;
      if (!text) {
        return res.status(400).json({ error: "Text is required" });
      }
      const generatedDoc = await generateStructuredPdfFromText(text);
      return res.json(generatedDoc);
    } catch (error) {
      console.error("PDF generation from text endpoint failed:", error);
      return res.status(500).json({
        error: "Failed to generate PDF from text",
        message: error instanceof Error ? error.message : "Unknown error",
      });
    }
  });

  // Suggestions endpoint
  app.post("/api/suggestions", (req, res) => {
    return res.json([
      {
        title: "متجر عطور فاخر",
        desc: "تصميم متجر إلكتروني جذاب وتفاعلي للمنتجات الراقية",
        prompt: "صمم لي متجر عطور فاخر بتأثيرات زجاجية (Glassmorphic) وسلة مشتريات تفاعلية وحركات دخول انسيابية",
      },
      {
        title: "عيادة طبية متكاملة",
        desc: "موقع طبي احترافي مع حجز مواعيد وتنسيق ذكي",
        prompt: "صمم موقعاً لعيادة طبية حديثة يشمل واجهة حجز مواعيد تفاعلية، معرض لخدمات العيادة، وقائمة الأطباء بتصميم أنيق",
      },
      {
        title: "لوحة تحكم SaaS",
        desc: "تخطيط احترافي لعرض البيانات والرسوم البيانية",
        prompt: "صمم لوحة تحكم سحابية (SaaS Dashboard) لعرض مبيعات شركة مع فلاتر فرز حية، ورسوم بيانية تفاعلية بلغة جافا سكريبت",
      },
      {
        title: "معرض أعمال للمصممين",
        desc: "موقع شخصي لعرض المشاريع بتأثيرات ثلاثية الأبعاد",
        prompt: "صمم موقع معرض أعمال شخصي لمصمم واجهات مستخدم يشمل بطاقات مشاريع تفاعلية مع تأثير الـ 3D Tilt ونموذج تواصل مخصص",
      },
    ]);
  });

  // Search API endpoint powered by DuckDuckGo Search (DDGS)
  app.post("/api/search", async (req, res) => {
    const { query, isOmni, options } = req.body;
    if (!query || typeof query !== "string") {
      return res.status(400).json({ error: "query is required" });
    }
    try {
      console.log(`[API Search Route] Query: "${query}", isOmni: ${!!isOmni}, Options:`, options);
      const searchResults = await runApexSearch(query, { intent: "answer", isOmni: !!isOmni, ...options });
      return res.json(searchResults);
    } catch (err: any) {
      console.error("[API Search Route] Error during search:", err);
      return res.status(500).json({ error: err.message || "Search failed" });
    }
  });

  // ── APEX UNBOUND: Dedicated multi-agent web generation endpoint ──────────────────
  // Streams phase-by-phase SSE events as each agent completes its work
  app.post("/api/unbound", async (req, res) => {
    const { message, conversationHistory, spec, searchResults, selectedChoices, isFollowUp } = req.body;

    if (!message || typeof message !== "string") {
      return res.status(400).json({ error: "message is required" });
    }

    const openrouterKey = process.env.OPENROUTER_API_KEY || process.env.DEEPSEEK_API_KEY;
    if (!openrouterKey) {
      return res.status(500).json({ error: "OPENROUTER_API_KEY is not configured" });
    }

    // Set up SSE for real-time streaming
    res.setHeader("Content-Type", "text/event-stream");
    res.setHeader("Cache-Control", "no-cache");
    res.setHeader("Connection", "keep-alive");
    res.setHeader("X-Accel-Buffering", "no");
    res.flushHeaders();

    const sendEvent = (data: object) => {
      if (!res.writableEnded) {
        res.write(`data: ${JSON.stringify(data)}\n\n`);
      }
    };

    try {
      const isOpenRouter = openrouterKey.startsWith("sk-or-");
      const client = new OpenAI({
        apiKey: openrouterKey,
        baseURL: isOpenRouter ? "https://openrouter.ai/api/v1" : "https://api.deepseek.com",
        defaultHeaders: {
          "HTTP-Referer": "https://apex-chat.vercel.app",
          "X-Title": "Apex Chat",
        }
      });

      const result = await runUnboundPipeline(
        client,
        {
          message,
          conversationHistory: conversationHistory || [],
          spec,
          searchResults,
          selectedChoices,
          isFollowUp,
        },
        (chunk) => {
          if (chunk.content) {
            sendEvent({ type: "content", content: chunk.content });
          }
          if (chunk.phase) {
            sendEvent({ type: "phase", phase: chunk.phase });
          }
          if (chunk.questions) {
            sendEvent({
              type: "question",
              questions: chunk.questions,
              spec: chunk.spec,
              searchResults: chunk.searchResults,
            });
          }
        }
      );

      if (result.isPaused) {
        console.log("[APEX Unbound] Pipeline paused for design questionnaire");
      } else {
        sendEvent({ type: "final", content: result.formattedOutput });
        sendEvent({ type: "done" });
      }
    } catch (err: any) {
      console.error("[APEX Unbound] Pipeline error:", err);
      sendEvent({ type: "error", error: err.message || "Pipeline failed" });
    } finally {
      res.end();
    }
  });

  // ❌ DEPRECATED: Voucher redemption endpoint removed
  // Voucher logic is now handled 100% client-side via Firestore SDK
  // See: client/src/lib/subscription-store.ts -> redeemVoucher()
  // 
  // Why removed:
  // - This endpoint had NO database interaction (stateless mock)
  // - No atomic transactions (race conditions possible)
  // - No wallet updates to Firestore
  // - Vouchers stored in Firestore, not hardcoded in schema.ts
  // 
  // If this route is accidentally called, return a helpful error
  app.post("/api/voucher/redeem", (req, res) => {
    return res.status(410).json({
      success: false,
      error: "DEPRECATED_ENDPOINT",
      message: "This endpoint has been removed. Vouchers are now redeemed client-side via Firebase.",
      details: "Please ensure your client app is using the latest subscription-store.ts logic."
    });
  });

  // Generate 3 design concepts based on the user's prompt
  app.post("/api/generate-concepts", async (req, res) => {
    try {
      const { prompt } = req.body;
      if (!prompt || typeof prompt !== "string" || prompt.trim().length < 5) {
        return res.status(400).json({ error: "Invalid prompt" });
      }

      const openrouterKey = process.env.OPENROUTER_API_KEY || process.env.DEEPSEEK_API_KEY;
      if (!openrouterKey) {
        return res.json(getFallbackConcepts(prompt));
      }

      const client = new OpenAI({
        apiKey: openrouterKey,
        baseURL: "https://openrouter.ai/api/v1",
        defaultHeaders: {
          "HTTP-Referer": "https://apex-chat.vercel.app",
          "X-Title": "Apex Chat",
        }
      });

      const systemPrompt = `You are a creative UI/UX web designer and product architect. Given a user's prompt (in Arabic or English) describing a website they want to build, generate a prompt-specific question and exactly 3 highly distinct choices/answers for the user to select from to configure their website design and features.
The question must be in Arabic, tailored specifically to the user's website idea (e.g. if they ask for a perfume website, ask: "ما هو الطابع الإبداعي والوظيفة التي تفضلها لمتجر العطور الخاص بك؟").
Each choice must represent a totally different design direction, layout, and feature set. Never repeat the same style.
You must return the response as a JSON object containing "question" (string) and "choices" (array of exactly 3 objects).
Return ONLY valid JSON. No markdown backticks, no markdown formatting, no other text.

JSON structure:
{
  "question": "Arabic question tailored specifically to the website idea",
  "choices": [
    {
      "title": "Short option title in Arabic (e.g. ✨ طابع ملكي زجاجي)",
      "description": "Detailed option description in Arabic (e.g. واجهة مظلمة فاخرة مع حواف ذهبية نيون وتأثير زجاجي، وعرض دائري للمنتجات).",
      "theme": "A theme keyword like 'glassmorphism', 'neobrutalism', 'minimalist-dark', 'cyberpunk', 'warm-organic', 'luxury-gold'"
    }
  ]
}`;

      const response = await client.chat.completions.create({
        model: "google/gemini-2.5-flash",
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `Generate a question and 3 choices for: "${prompt}"` },
        ],
        temperature: 0.7,
        max_tokens: 800,
      });

      const content = response.choices[0]?.message?.content || "";
      let concepts;
      try {
        const parsed = robustJsonParse(content);
        if (parsed.question && Array.isArray(parsed.choices)) {
          concepts = parsed;
        } else {
          const choicesArray = Array.isArray(parsed) ? parsed : (parsed.choices || Object.values(parsed)[0]);
          concepts = {
            question: `ما هو التوجه والخصائص التي تفضلها لموقع ${prompt}؟`,
            choices: choicesArray
          };
        }
      } catch (e) {
        console.error("Failed to parse AI concept response, using fallback. Raw content:", content);
        concepts = getFallbackConcepts(prompt);
      }

      if (!concepts || !concepts.question || !Array.isArray(concepts.choices) || concepts.choices.length < 3) {
        return res.json(getFallbackConcepts(prompt));
      }

      concepts.choices = concepts.choices.slice(0, 3);
      return res.json(concepts);
    } catch (error) {
      console.error("Error generating concepts:", error);
      return res.json(getFallbackConcepts(req.body.prompt || ""));
    }
  });

  // Website preview creation endpoint
  app.post("/api/preview", (req, res) => {
    const { html } = req.body;
    if (typeof html !== "string") {
      return res.status(400).json({ error: "Invalid html content" });
    }

    // Strict Size Limit: 2MB to prevent DoS attacks
    if (html.length > 2 * 1024 * 1024) {
      return res.status(413).json({ error: "Payload too large. Maximum size is 2MB." });
    }

    // Prevent memory leaks / abuse (Strict LRU implementation)
    if (previewStore.size >= 500) {
      const firstKey = previewStore.keys().next().value;
      if (firstKey) previewStore.delete(firstKey);
    }

    // Optionally sanitize HTML here if needed, but since it's meant to execute JS for code generation, 
    // we rely on CSP and sandbox headers in the GET route.
    const id = randomUUID();
    previewStore.set(id, { html, createdAt: Date.now() });
    return res.json({ id });
  });

  // Website preview rendering endpoint (Direct HTTP serving)
  app.get("/preview/:id", (req, res) => {
    const { id } = req.params;
    const data = previewStore.get(id);
    if (!data) {
      return res.status(404).send(`
        <!DOCTYPE html>
        <html lang="ar" dir="rtl">
        <head>
          <title>رابط المعاينة منتهي الصلاحية · Preview Expired</title>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@400;600;700&display=swap" rel="stylesheet">
          <style>
            body {
              background: radial-gradient(circle at 10% 20%, rgba(139, 92, 246, 0.08) 0%, transparent 40%),
                          radial-gradient(circle at 90% 80%, rgba(236, 72, 153, 0.06) 0%, transparent 40%),
                          #030303;
              color: #f4f4f5;
              font-family: 'Cairo', system-ui, -apple-system, sans-serif;
              display: flex;
              justify-content: center;
              align-items: center;
              height: 100vh;
              margin: 0;
              padding: 1.5rem;
              box-sizing: border-box;
              overflow: hidden;
            }
            .card {
              text-align: center;
              border: 1px solid rgba(139, 92, 246, 0.15);
              padding: 3rem 2rem;
              border-radius: 28px;
              background: rgba(15, 15, 18, 0.65);
              backdrop-filter: blur(24px);
              -webkit-backdrop-filter: blur(24px);
              max-width: 450px;
              width: 100%;
              box-shadow: 0 30px 60px rgba(0, 0, 0, 0.8),
                          inset 0 1px 0 rgba(255, 255, 255, 0.08),
                          0 0 40px rgba(139, 92, 246, 0.03);
              position: relative;
              overflow: hidden;
              animation: slideUp 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards;
            }
            .card::before {
              content: '';
              position: absolute;
              top: 0;
              left: 0;
              right: 0;
              height: 3px;
              background: linear-gradient(90deg, #8b5cf6, #ec4899, #3b82f6);
            }
            .icon-wrapper {
              width: 64px;
              height: 64px;
              border-radius: 20px;
              background: rgba(239, 68, 68, 0.1);
              border: 1px solid rgba(239, 68, 68, 0.2);
              display: flex;
              align-items: center;
              justify-content: center;
              margin: 0 auto 1.5rem;
              color: #ef4444;
              font-size: 1.75rem;
              font-weight: bold;
              animation: pulseError 2s infinite ease-in-out;
            }
            h1 {
              color: #f4f4f5;
              margin: 0 0 1rem;
              font-size: 1.6rem;
              font-weight: 700;
              letter-spacing: -0.02em;
            }
            p {
              font-size: 0.95rem;
              color: #a1a1aa;
              line-height: 1.6;
              margin: 0;
            }
            .btn-back {
              display: inline-flex;
              align-items: center;
              justify-content: center;
              margin-top: 2rem;
              padding: 0.75rem 1.75rem;
              background: linear-gradient(90deg, #8b5cf6, #6366f1);
              color: white;
              text-decoration: none;
              border-radius: 14px;
              font-size: 0.9rem;
              font-weight: 600;
              box-shadow: 0 10px 20px rgba(139, 92, 246, 0.2);
              transition: all 0.2s ease;
            }
            .btn-back:hover {
              transform: translateY(-2px);
              box-shadow: 0 15px 25px rgba(139, 92, 246, 0.3);
              background: linear-gradient(90deg, #9b6bf7, #7376f2);
            }
            .btn-back:active {
              transform: translateY(0);
            }
            @keyframes slideUp {
              from { opacity: 0; transform: translateY(20px); }
              to { opacity: 1; transform: translateY(0); }
            }
            @keyframes pulseError {
              0%, 100% { box-shadow: 0 0 0 0 rgba(239, 68, 68, 0.2); }
              50% { box-shadow: 0 0 0 8px rgba(239, 68, 68, 0); }
            }
          </style>
        </head>
        <body>
          <div class="card">
            <div class="icon-wrapper">⚠️</div>
            <h1>رابط المعاينة منتهي الصلاحية</h1>
            <p>انتهت صلاحية هذه المعاينة أو لم يتم العثور عليها. يرجى إعادة تشغيل المعاينة من المحادثة مجدداً.</p>
            <p style="font-size: 0.8rem; color: #71717a; margin-top: 0.5rem; font-family: system-ui, sans-serif;" dir="ltr">
              Preview expired or not found. Please regenerate it again from the chat.
            </p>
            <a href="javascript:window.close()" class="btn-back">إغلاق الصفحة</a>
          </div>
        </body>
        </html>
      `);
    }

    res.setHeader("Content-Type", "text/html; charset=utf-8");
    // Enforce strict Content Security Policy to prevent data exfiltration and cross-site actions
    res.setHeader("Content-Security-Policy", "default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: https://fonts.googleapis.com https://fonts.gstatic.com; frame-ancestors 'self';");
    res.setHeader("X-Content-Type-Options", "nosniff");
    res.setHeader("X-Frame-Options", "SAMEORIGIN");
    return res.send(data.html);
  });

  // Health check endpoint
  app.get("/api/health", (_req, res) => {
    res.json({
      status: "ok",
      provider: "openrouter",
      apiConfigured: !!(process.env.OPENROUTER_API_KEY || process.env.DEEPSEEK_API_KEY),
    });
  });

  return httpServer;
}

function getFallbackConcepts(prompt: string) {
  const p = (prompt || "").toLowerCase();
  let question = "ما هو التوجه والأسلوب الذي تفضله لتصميم موقعك؟";
  let choices = [
    {
      title: "✨ زجاجي عصري (Glassmorphism)",
      description: "تصميم عصري جذاب بخلفيات ضبابية شفافة وتدرجات نيون ناعمة، يمنح شعوراً بالحداثة والعمق البصري.",
      theme: "glassmorphism"
    },
    {
      title: "🎨 نيوبروتالزم تفاعلي (Neobrutalism)",
      description: "تصميم شبابي جريء بتباين عالٍ، حدود سوداء سميكة، وألوان حيوية نابضة بالحياة تتفاعل فوراً مع نقرات المستخدم.",
      theme: "neobrutalism"
    },
    {
      title: "🖤 ملكي فاخر (Luxury Royal)",
      description: "مظهر كلاسيكي فاخر بألوان كحلي داكن وذهبي ملكي مع خطوط عربية أنيقة ومؤثرات ظهور تدريجي تعكس الفخامة والأناقة.",
      theme: "luxury-gold"
    }
  ];

  if (p.includes("مطعم") || p.includes("أكل") || p.includes("طعام") || p.includes("burger") || p.includes("food") || p.includes("restaurant") || p.includes("cafe") || p.includes("قهوة") || p.includes("كافيه")) {
    question = "ما هو الطابع البصري وتجربة المستخدم المفضلة لموقع مطعمك؟";
    choices = [
      {
        title: "🍔 مودرن داكن وجريء",
        description: "تصميم داكن غامر مع تدرجات لونية برتقالية وحمراء متوهجة، ومؤثرات حركية جذابة لبطاقات الطعام وقائمة تفاعلية.",
        theme: "cyberpunk"
      },
      {
        title: "✨ كلاسيكي دافئ وراقي",
        description: "طابع ملكي أنيق بألوان كحلي وذهبي، يركز على حجز الطاولات، التقييمات، وقصة المطعم مع خطوط كلاسيكية فاخرة.",
        theme: "luxury-gold"
      },
      {
        title: "🌱 نظيف وصديق للبيئة",
        description: "ألوان خضراء هادئة وخلفية بيج مريحة، يعرض المكونات الطازجة بشكل تفاعلي مع واجهة تصفح فائقة الخفة.",
        theme: "warm-organic"
      }
    ];
  } else if (p.includes("متجر") || p.includes("بيع") || p.includes("شراء") || p.includes("shop") || p.includes("store") || p.includes("e-commerce") || p.includes("سلة")) {
    question = "ما هي واجهة العرض وسلة المشتريات التي تفضلها لمتجرك الإلكتروني؟";
    choices = [
      {
        title: "🛍️ متجر زجاجي نيون تفاعلي",
        description: "تصميم زجاجي (Glassmorphism) مع ألوان نيون متدرجة، سلة مشتريات منبثقة، وتأثيرات حركية عند تمرير الماوس على المنتجات.",
        theme: "glassmorphism"
      },
      {
        title: "🖤 مينيومالست كلاسيكي صامت",
        description: "مظهر أحادي اللون (أبيض وأسود) فاخر، خطوط رفيعة وأنيقة، تركيز كامل على صور المنتجات وتكبير سلس عند التمرير.",
        theme: "minimalist-dark"
      },
      {
        title: "🎨 نيوبروتالزم جريء وعصري",
        description: "حدود سوداء عريضة، ألوان باستيل زاهية، وتفاعلات بصرية فورية ومرحة تعطي انطباعاً شبابياً وحيوياً.",
        theme: "neobrutalism"
      }
    ];
  } else if (p.includes("لعبة") || p.includes("العاب") || p.includes("game") || p.includes("play")) {
    question = "ما هو أسلوب التفاعل والواجهة المفضلة لموقع الألعاب الخاص بك؟";
    choices = [
      {
        title: "🎮 سايبربانك غامر (Cyberpunk)",
        description: "خلفية داكنة جداً مع خطوط نيون وردية وزرقاء متوهجة، مؤثرات صوتية بصرية تفاعلية، ولوحة تحكم عصرية بالكامل.",
        theme: "cyberpunk"
      },
      {
        title: "⚡ واجهة أركيد حيوية (Arcade)",
        description: "ألوان صفراء وحمراء ساطعة، خطوط بيكسل كلاسيكية، تفاعل بملء الشاشة مع بطاقات نتائج متحركة وممتعة.",
        theme: "neobrutalism"
      },
      {
        title: "✨ غامض ومظلم (Mystic Dark)",
        description: "تدرجات بنفسجية ورمادية عميقة، مؤثرات ضبابية زجاجية، وظلال ناعمة تعطي طابعاً غامضاً ومثيراً للاهتمام.",
        theme: "glassmorphism"
      }
    ];
  } else if (p.includes("طب") || p.includes("عيادة") || p.includes("دكتور") || p.includes("مستشفى") || p.includes("clinic") || p.includes("doctor") || p.includes("medical")) {
    question = "ما هو أسلوب حجز المواعيد والعرض الأنسب لعيادتك الطبية؟";
    choices = [
      {
        title: "🏥 زجاجي ناعم مع حجز مباشر",
        description: "تصميم مريح مع خلفيات شبه شفافة بلون سماوي مهدئ، ونظام حجز مواعيد فوري تفاعلي.",
        theme: "glassmorphism"
      },
      {
        title: "💼 رسمي وعملي مبسط",
        description: "ألوان زرقاء وبيضاء كلاسيكية، تركيز كامل على عرض الأقسام الطبية، أوقات العمل، والاتصال الفوري.",
        theme: "minimalist-dark"
      },
      {
        title: "✨ حديث وبطاقات تفاعلية",
        description: "عرض الخدمات والأطباء في بطاقات عائمة وتأثيرات حركية سلسة لجذب ثقة المرضى.",
        theme: "luxury-gold"
      }
    ];
  }

  return { question, choices };
}

